audit_header: false
title: "Guaranteed Offer"
description: Kwasi Bowie, a top Real Estate Agent in Seattle, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
client:
  name: Kwasi Bowie
  title:
  license_number:
  about_markdown: |

  market: Seattle
  brand: Kwasi Homes
  brokerage: Compass
  address: 2033 6th Ave, Suite 600 Seattle, WA 98121
  phone: 206-854-4132
  phone_type:
  phone2:
  phone2_type:
  email: kwasib@kwasihomes.com
  url: https://www.kwasihomes.com

images:
  client_headshot_path: /img/headshot.png
  hero_logo_path: /img/logo.png
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg

site_colors:
  brand_color: '#000'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
